-- Migration: create table for idempotent Cakto webhook processing
-- Execute this in the Supabase SQL editor or via CLI

create table if not exists public.cakto_webhook_events (
  id bigint generated by default as identity primary key,
  event_id text not null unique,
  event_type text,
  status text,
  customer_email text,
  payment_id text,
  subscription_id text,
  payload jsonb not null,
  processed_at timestamptz not null default now()
);

create index if not exists idx_cakto_webhook_events_processed_at
  on public.cakto_webhook_events (processed_at desc);
